### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MariaRsA** [Rolfff/Visametric-Termin-Bot#5]
Hello again,
ich have problem with this Error 
Traceback (most recent call last):
  File "C:\Users\maria.azad\Downloads\Visametric-Termin-Bot-master\Visametric-Termin-Bot-master\termin-bot.py", line 317, in <module>
    s = Search()
        ^^^^^^^^
  File "C:\Users\maria.azad\Downloads\Visametric-Termin-Bot-master\Visametric-Termin-Bot-master\termin-bot.py", line 59, in __init__
    options.binary_location = c.install["win_binary_location": r'C:\Program Files\Mozilla Firefox\firefox.exe']
                              ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'slice'

could you please help me?
can you speak German?
Thank you so much

**Comment by MariaRsA** [comment]
This is a Code Change screenshot 

![image](https://github.com/Rolfff/Visametric-Termin-Bot/assets/138564875/4332f469-6298-458a-9ff4-5654ca738b86)

**Comment by Rolfff** [comment]
Ja, es hat sich alles geändert. 
Ich habe das Script jetzt umgeschrieben.  -> https://github.com/Rolfff/Visametric-Termin-Bot/tree/new_botdetection
Ich teste es noch kurz mit Windows. Aber dann solltest du es neu runterladen.
Dieser Fehler hat sich damit erledigt.

**Comment by Rolfff** [comment]
Ich habe den Master-Branch geupdatet.
Du solltest noch "pip install undetected-chromedriver" und den Chrom Browser installieren.

**Comment by MariaRsA** [comment]
Vielen Dank.
Ich habe nochmal probiert. Es kommt ein Fehler vor in dem Schritt wo ein Verifizierung Code per Email versendet wird. Den Browser wird automatisch geschlossen. Ich habe den Verifizierungscode erhalten aber man kann den Code nicht eingeben.  
Exception ignored in: <function Chrome.__del__ at 0x00000283F59DE160>
Traceback (most recent call last):
  File "C:\Users\maria.azad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\undetected_chromedriver\__init__.py", line 793, in __del__
  File "C:\Users\maria.azad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\undetected_chromedriver\__init__.py", line 748, in quit
OSError: [WinError 6] Das Handle ist ungültig

**Comment by Rolfff** [comment]
Wird dir gesagt an welcher Zeilennummer in der termin-bot.py das Script beendet wird? 
Du kannst vor die Zeile `time.sleep(600)` einfügen. Dann hast du 10 Minuten zeit die restlichen Schritte manuell zu machen.
Wahrscheinlich irgenwann nach [325](https://github.com/Rolfff/Visametric-Termin-Bot/blob/b889368d0c9e0d0c26d3c003e46338ad32f6e7ee/termin-bot.py#L235) ?
